# Generated by Django 5.2.5 on 2025-09-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="companies",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="companies.company"
            ),
        ),
    ]
