# Generated by Django 5.2.5 on 2025-09-29 11:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Capability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=60, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="RelationshipType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roller",
            },
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("person", "Kişi"), ("organization", "Kuruluş")],
                        default="person",
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=120)),
                ("last_name", models.CharField(blank=True, max_length=120)),
                (
                    "legal_name",
                    models.CharField(blank=True, max_length=255, verbose_name="Unvan"),
                ),
                (
                    "trade_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ticari Ad"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=64)),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Vergi No/TCKN"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parties",
                        to="companies.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartyCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_grants",
                        to="parties.capability",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_capabilities",
                        to="companies.company",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capabilities",
                        to="parties.party",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_from", models.DateField(default=django.utils.timezone.now)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_relationships",
                        to="companies.company",
                    ),
                ),
                (
                    "from_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rels_from",
                        to="parties.party",
                    ),
                ),
                (
                    "to_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rels_to",
                        to="parties.party",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relationships",
                        to="parties.relationshiptype",
                    ),
                ),
                (
                    "from_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rels_from_as_role",
                        to="parties.role",
                    ),
                ),
                (
                    "to_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rels_to_as_role",
                        to="parties.role",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartyRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_from", models.DateField(default=django.utils.timezone.now)),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_roles",
                        to="companies.company",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="parties.party",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_roles",
                        to="parties.role",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoleCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="parties.capability",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capabilities",
                        to="parties.role",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="party",
            index=models.Index(
                fields=["company", "type"], name="parties_par_company_370663_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="party",
            index=models.Index(
                fields=["company", "email"], name="parties_par_company_676c84_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="party",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tax_id", ""), _negated=True),
                fields=("company", "tax_id"),
                name="uq_party_company_tax_id_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="partycapability",
            constraint=models.UniqueConstraint(
                fields=("party", "capability", "company"),
                name="uq_party_capability_in_scope",
            ),
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=models.Index(
                fields=["company", "type"], name="parties_rel_company_3c4600_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=models.Index(
                fields=["company", "from_party"], name="parties_rel_company_0ca824_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=models.Index(
                fields=["company", "to_party"], name="parties_rel_company_594d5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partyrole",
            index=models.Index(
                fields=["company", "role"], name="parties_par_company_ad3d91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partyrole",
            index=models.Index(
                fields=["party", "role"], name="parties_par_party_i_028765_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="partyrole",
            constraint=models.UniqueConstraint(
                fields=("party", "role", "company"),
                name="uq_party_role_unique_in_scope",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rolecapability",
            unique_together={("role", "capability")},
        ),
    ]
